package br.com.joqi.testes.gui;

public class EditorConsultaForm extends javax.swing.JFrame {

	/** Creates new form EditorConsultaForm */
	public EditorConsultaForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		btnExecutar = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		textAreaQuery = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		tableResultado = new javax.swing.JTable();
		lbStatus = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Editor de consultas");

		btnExecutar.setText("Executar...");

		textAreaQuery.setColumns(20);
		textAreaQuery.setRows(5);
		jScrollPane1.setViewportView(textAreaQuery);

		jScrollPane2.setViewportView(tableResultado);

		jScrollPane3.setViewportView(jScrollPane2);

		lbStatus.setText("");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(btnExecutar))
										.addComponent(lbStatus))
								.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(btnExecutar, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lbStatus)
										.addContainerGap())
				);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton btnExecutar;
	private javax.swing.JLabel lbStatus;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable tableResultado;
	private javax.swing.JTextArea textAreaQuery;

	// End of variables declaration

	public javax.swing.JTable getTableResultado() {
		return tableResultado;
	}

	public javax.swing.JLabel getLbStatus() {
		return lbStatus;
	}

	public javax.swing.JTextArea getTextAreaQuery() {
		return textAreaQuery;
	}

	public javax.swing.JButton getBtnExecutar() {
		return btnExecutar;
	}

	public void setTableResultado(javax.swing.JTable tableResultado) {
		this.tableResultado = tableResultado;
	}

}
