package br.com.joqi.testes;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import br.com.joqi.testes.modelo.Artista;
import br.com.joqi.testes.modelo.Disco;
import br.com.joqi.testes.modelo.Genero;

public class BancoConsulta {

	private List<Disco> discos;
	private List<Artista> artistas;
	private List<Genero> generos;

	public BancoConsulta() {
		discos = criaListaDiscos();
		artistas = criaListaColecoes();
		generos = criaListaGeneros();
	}

	private List<Genero> criaListaGeneros() {
		return new ArrayList<Genero>(Arrays.asList(
				new Genero(1, "Metal"),
				new Genero(2, "Reggae"),
				new Genero(3, "Pop")
				));
	}

	private List<Artista> criaListaColecoes() {
		return new ArrayList<Artista>(Arrays.asList(
				new Artista(1, "Black Sabbath", 1),
				new Artista(2, "Iron Maiden", 1),
				new Artista(3, "Metallica", 1),
				new Artista(4, "Judas Priest", 1),
				new Artista(5, "Motörhead", 1),
				new Artista(6, "Slayer", 1),
				new Artista(7, "Megadeth", 1),
				new Artista(8, "Venom", 1),
				new Artista(9, "Pantera", 1),
				new Artista(10, "Death", 1),
				new Artista(11, "Ozzy Osbourne", 1),
				new Artista(12, "Queensrcyhe", 1),
				new Artista(13, "Dream Theater", 1),
				new Artista(14, "Celtic Frost", 1),
				new Artista(15, "Manowar", 1),
				new Artista(16, "Dio", 1),
				new Artista(17, "Mercyful Fate", 1),
				new Artista(18, "Helloween", 1),
				new Artista(19, "Anthrax", 1),
				new Artista(20, "Bathory", 1),
				new Artista(21, "Napalm Death", 1),
				new Artista(22, "Carcass", 1),
				new Artista(23, "Alice in Chains", 1),
				new Artista(24, "Sepultura", 1),
				new Artista(25, "Mötley Crüe", 1),
				new Artista(26, "Scorpions", 1),
				new Artista(27, "Morbid Angel", 1),
				new Artista(28, "Tool", 1),
				new Artista(29, "Mayhem", 1),
				new Artista(30, "Korn", 1),
				new Artista(31, "Opeth", 1),
				new Artista(32, "Emperor", 1),
				new Artista(33, "Rainbow", 1),
				new Artista(34, "Soundgarden", 1),
				new Artista(35, "Exodus", 1),
				new Artista(36, "Possessed", 1),
				new Artista(37, "Blind Guardian", 1),
				new Artista(38, "Cannibal Corpse", 1),
				new Artista(39, "Testament", 1),
				new Artista(40, "Faith No More", 1),
				new Artista(41, "King Diamond", 1),
				new Artista(42, "Suicidal Tendencies", 1),
				new Artista(43, "Accept", 1),
				new Artista(44, "Fates Warning", 1),
				new Artista(45, "Overkill", 1),
				new Artista(46, "Symphony X", 1),
				new Artista(47, "Yngwie Malmsteen", 1),
				new Artista(48, "Kreator", 1),
				new Artista(49, "Deicide", 1),
				new Artista(50, "Burzum", 1),
				new Artista(51, "At the Gates", 1),
				new Artista(52, "System of a Down", 1),
				new Artista(53, "Candlemass", 1),
				new Artista(54, "Saxon", 1),
				new Artista(55, "Slipknot", 1),
				new Artista(56, "In Flames", 1),
				new Artista(57, "Rage Against the Machine", 1),
				new Artista(58, "Children of Bodom", 1),
				new Artista(59, "Voivod", 1),
				new Artista(60, "Machine Head", 1),
				new Artista(61, "Dimmu Borgir", 1),
				new Artista(62, "Diamond Head", 1),
				new Artista(63, "Neurosis", 1),
				new Artista(64, "Metal Church", 1),
				new Artista(65, "Savatage", 1),
				new Artista(66, "Type O Negative", 1),
				new Artista(67, "Darkthrone", 1),
				new Artista(68, "DRI", 1),
				new Artista(69, "My Dying Bride", 1),
				new Artista(70, "Sodom", 1),
				new Artista(71, "W.A.S.P.", 1),
				new Artista(72, "Immortal", 1),
				new Artista(73, "Iced Earth", 1),
				new Artista(74, "Twisted Sister", 1),
				new Artista(75, "Cradle of Filth", 1),
				new Artista(76, "Ministry", 1),
				new Artista(77, "Terrorizer", 1),
				new Artista(78, "Annihilator", 1),
				new Artista(79, "Danzig", 1),
				new Artista(80, "Dokken", 1),
				new Artista(81, "White Zombie", 1),
				new Artista(82, "HammerFall", 1),
				new Artista(83, "Gamma Ray", 1),
				new Artista(84, "Edge of Sanity", 1),
				new Artista(85, "St,Vitus", 1),
				new Artista(86, "Nevermore", 1),
				new Artista(87, "Pentagram", 1),
				new Artista(88, "Budgie", 1),
				new Artista(89, "Fear Factory", 1),
				new Artista(90, "Mastodon", 1),
				new Artista(91, "Meshuggah", 1),
				new Artista(92, "Entombed", 1),
				new Artista(93, "Lamb of God", 1),
				new Artista(94, "Suffocation", 1),
				new Artista(95, "Skid Row", 1),
				new Artista(96, "Raven", 1),
				new Artista(97, "Therion", 1),
				new Artista(98, "Trouble", 1),
				new Artista(99, "Stratovarius", 1),
				new Artista(100, "Atheist", 1),
				new Artista(101, "Natiruts", 2),
				new Artista(102, "Natural Dread Killaz", 2),
				new Artista(103, "Nayah", 2),
				new Artista(104, "Negril", 2),
				new Artista(105, "Negroots", 2),
				new Artista(106, "Neto Trindade", 2),
				new Artista(107, "Noção Rasta", 2),
				new Artista(108, "Nomad", 2),
				new Artista(109, "Nuevas Raices", 2),
				new Artista(110, "Onda R", 2),
				new Artista(111, "Pato Banton", 2),
				new Artista(112, "Patrice", 2),
				new Artista(113, "Peter Tosh", 2),
				new Artista(114, "Planet Roots", 2),
				new Artista(115, "Planta e Raiz", 2),
				new Artista(116, "Ponto De Equilibrio", 2),
				new Artista(117, "Praiera", 2),
				new Artista(118, "Prato Feito", 2),
				new Artista(119, "Rabo jah raia", 2),
				new Artista(120, "Raiz do Porto", 2),
				new Artista(121, "Raizes Rasta", 2),
				new Artista(122, "Raiztafari", 2),
				new Artista(123, "Rastaclone", 2),
				new Artista(124, "Rastafeeling", 2),
				new Artista(125, "Rebel Lion", 2),
				new Artista(126, "Reggalize", 2),
				new Artista(127, "Richie Spice", 2),
				new Artista(128, "S.O.J.A", 2),
				new Artista(129, "Semente Reggada", 2),
				new Artista(130, "Sensimilla Dub", 2),
				new Artista(131, "Shamanes", 2),
				new Artista(132, "Sine Calmon", 2),
				new Artista(133, "Sinsémilia", 2),
				new Artista(134, "Sizzla", 2),
				new Artista(135, "Solarise", 2),
				new Artista(136, "Soldiers of Jah Army", 2),
				new Artista(137, "Steel Pulse", 2),
				new Artista(138, "Súditos do Reggae", 2),
				new Artista(139, "Tafari Roots", 2),
				new Artista(140, "Tanya Stephens", 2),
				new Artista(141, "Temptations", 2),
				new Artista(142, "The Gladiators", 2),
				new Artista(143, "The Skatalites", 2),
				new Artista(144, "To Fly", 2),
				new Artista(145, "Tommy Torres", 2),
				new Artista(146, "Toots And The Maytals", 2),
				new Artista(147, "Tribo de Jah", 2),
				new Artista(148, "Trilhas e Raízes", 2),
				new Artista(149, "Trio Carcará", 2),
				new Artista(150, "Tryo", 2),
				new Artista(151, "Tupi e Nagô", 2),
				new Artista(152, "UB40", 2),
				new Artista(153, "Usina Reggae", 2),
				new Artista(154, "Vibração Nativa", 2),
				new Artista(155, "Vibrações Rasta", 2),
				new Artista(156, "X Rabbits", 2),
				new Artista(157, "Yellowman", 2),
				new Artista(158, "YoManaHo", 2),
				new Artista(159, "Zach Ashton", 2),
				new Artista(160, "Zandaroots", 2),
				new Artista(161, "Ziggy Marley", 2),
				new Artista(162, "", 2),
				new Artista(163, "Edson Gomes", 2),
				new Artista(164, "Edu Ribeiro", 2),
				new Artista(165, "Ekolu", 2),
				new Artista(166, "Expressão Regueira", 2),
				new Artista(167, "Filhos Do Totem", 2),
				new Artista(168, "Filosofia Reggae", 2),
				new Artista(169, "Forças do Gueto", 2),
				new Artista(170, "Gabi e Os Manos de Jah", 2),
				new Artista(171, "Gentleman", 2),
				new Artista(172, "Gondwana", 2),
				new Artista(173, "Gregory Isaacs", 2),
				new Artista(174, "Groundation", 2),
				new Artista(175, "Horace Andy", 2),
				new Artista(176, "Iriê", 2),
				new Artista(177, "Israel Vibration", 2),
				new Artista(178, "Jaafa Reggae", 2),
				new Artista(179, "Jacob Miller", 2),
				new Artista(180, "Jah Cure", 2),
				new Artista(181, "Jah I Ras", 2),
				new Artista(182, "Jah Live", 2),
				new Artista(183, "Javaroots", 2),
				new Artista(184, "Jimmy Cliff", 2),
				new Artista(185, "Johnny Jack Mesclado", 2),
				new Artista(186, "Julian Marley", 2),
				new Artista(187, "Ka'au Crater Boys", 2),
				new Artista(188, "Kafu Banton", 2),
				new Artista(189, "Kana", 2),
				new Artista(190, "Kanabaus", 2),
				new Artista(191, "Kaymakan", 2),
				new Artista(192, "Khriz y Angel", 2),
				new Artista(193, "King Chango", 2),
				new Artista(194, "La Verdolaga", 2),
				new Artista(195, "Larry Marshall", 2),
				new Artista(196, "Leão de Judah", 2),
				new Artista(197, "Lee Perry", 2),
				new Artista(198, "Leões de Israel", 2),
				new Artista(199, "Libertus", 2),
				new Artista(200, "Lion Jump", 2),
				new Artista(201, "Los Baganas", 2),
				new Artista(202, "Los Cafres", 2),
				new Artista(203, "Los Pericos", 2),
				new Artista(204, "Luauê", 2),
				new Artista(205, "Luciano", 2),
				new Artista(206, "Macucos", 2),
				new Artista(207, "Mama Quilla", 2),
				new Artista(208, "Mano Bantu", 2),
				new Artista(209, "Marcinho do Surf", 2),
				new Artista(210, "Marlon Asher", 2),
				new Artista(211, "Maskavo", 2),
				new Artista(212, "Matisyahu", 2),
				new Artista(213, "Mato Seco", 2),
				new Artista(214, "Maverick", 2),
				new Artista(215, "Max Romeo", 2),
				new Artista(216, "Medida Salvadora", 2),
				new Artista(217, "Michael Franti & Spearhead", 2),
				new Artista(218, "Midnite", 2),
				new Artista(219, "Morgan Heritage", 2),
				new Artista(220, "Mosaico", 2),
				new Artista(221, "Mosiah Roots", 2),
				new Artista(222, "Mystical Roots", 2),
				new Artista(223, "Nação Forreggae", 2),
				new Artista(224, "", 2),
				new Artista(225, "2face Idibia", 2),
				new Artista(226, "A Cor do Reggae", 2),
				new Artista(227, "Abyssinians", 2),
				new Artista(228, "Acústico Reggae", 2),
				new Artista(229, "Adão Negro", 2),
				new Artista(230, "Afrodizia", 2),
				new Artista(231, "Afroman", 2),
				new Artista(232, "Akundum", 2),
				new Artista(233, "Alma D'Jem", 2),
				new Artista(234, "Alpha Blondy", 2),
				new Artista(235, "Anthony B.", 2),
				new Artista(236, "Anti-Babylon", 2),
				new Artista(237, "Antônio Brother", 2),
				new Artista(238, "Armandinho", 2),
				new Artista(239, "Augustus Pablo", 2),
				new Artista(240, "Ayakayô", 2),
				new Artista(241, "Ayo", 2),
				new Artista(242, "Bahiano", 2),
				new Artista(243, "Baião de Quatro", 2),
				new Artista(244, "Banda Nayah", 2),
				new Artista(245, "Beca Arruda", 2),
				new Artista(246, "Ben Roots", 2),
				new Artista(247, "Bennie Man", 2),
				new Artista(248, "Beres Hammond", 2),
				new Artista(249, "Bernard Lavilliers", 2),
				new Artista(250, "Black Uhuru", 2),
				new Artista(251, "Bob Marley", 2),
				new Artista(252, "Bob Marley & Lauryn Hill", 2),
				new Artista(253, "Bob Marley & The Wailers", 2),
				new Artista(254, "Bob Sinclar", 2),
				new Artista(255, "Bounty Killer", 2),
				new Artista(256, "Brisa Verde", 2),
				new Artista(257, "Brownman Revival", 2),
				new Artista(258, "Buju Banton", 2),
				new Artista(259, "Burning Spear", 2),
				new Artista(260, "Bushman", 2),
				new Artista(261, "Butch Helemano", 2),
				new Artista(262, "Canamaré", 2),
				new Artista(263, "Capleton", 2),
				new Artista(264, "Casaca", 2),
				new Artista(265, "Chaka Demus & Pliers", 2),
				new Artista(266, "Chicken Power", 2),
				new Artista(267, "Chimarruts", 2),
				new Artista(268, "Christafari", 2),
				new Artista(269, "Cidade Negra", 2),
				new Artista(270, "Circulo Rasta", 2),
				new Artista(271, "Cultura Profetica", 2),
				new Artista(272, "Culture", 2),
				new Artista(273, "Da'ville", 2),
				new Artista(274, "Damian Marley", 2),
				new Artista(275, "Dazaranha", 2),
				new Artista(276, "Dezarie", 2),
				new Artista(277, "Diamba", 2),
				new Artista(278, "Digo Cardkamp", 2),
				new Artista(279, "Djamborii Roots", 2),
				new Artista(280, "Don Carlos", 2),
				new Artista(281, "Dona Leda", 2),
				new Artista(282, "Dread Lion", 2),
				new Artista(283, "Dread Roots", 2),
				new Artista(284, "Dreadlock", 2),
				new Artista(285, "Dred Nox", 2),
				new Artista(286, "Du'Casco", 2),
				new Artista(287, "Easy Star All Stars", 2)
				));
	}

	private List<Disco> criaListaDiscos() {
		return null;
	}

}
